[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
pythonpath = "src"
testpaths = "tests"

[tool.mypy]
strict = true
mypy_path = "src"
ignore_missing_imports = true
